// Export all active components
export { default as VileadSidebar } from './VileadSidebar'
export { default as Header } from './Header'
export { default as Dashboard } from './Dashboard'
export { default as AccountantDashboard } from './AccountantDashboard'
export { default as SalesManagement } from './SalesManagement'
export { default as CustomersManagement } from './CustomersManagement'
export { default as OrderManagement } from './OrderManagement'
export { default as TaskManagement } from './TaskManagement'
export { default as ReportsManagement } from './ReportsManagement'
export { default as SettingsManagement } from './SettingsManagement'
export { default as CompanyManagement } from './CompanyManagement'
export { default as ChatbotAssistantNew } from './ChatbotAssistantNew'
export { default as EnhancedDashboardFilters } from './EnhancedDashboardFilters'
export { default as CustomerFilters } from './CustomerFilters'
export { default as CustomerEventsManager } from './CustomerEventsManager'
export { default as CustomerAnalytics } from './CustomerAnalytics'
export { default as CreateTaskModal } from './CreateTaskModal'
export { default as TaskDetailModal } from './TaskDetailModal'
export { default as CreateEventModal } from './CreateEventModal'
export { default as CreateOrderModal } from './CreateOrderModal'
export { default as OrderDetailModal } from './OrderDetailModal'
export { DepartmentModal, TeamModal } from './DepartmentTeamModals'